embed_assets: on
package_assets: always
package_path: assets

javascripts:
  common:
    - public/javascripts/default.js

stylesheets:
  common:
    - public/stylesheets/application.css
    - public/stylesheets/portfolio.css